# [사용법]
# 컨테이너 재시작
# docker-compose -f docker-compose.dev.yml -f docker-compose.kafka-rabbitmq.yml down
# docker-compose -f docker-compose.dev.yml -f docker-compose.kafka-rabbitmq.yml up -d --build
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DEFAULT_SCHEMA}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gdg_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gdg_network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gdg_network

  # API WAS (개발환경 단일)
  backend-api:
    container_name: backend
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
      - DEFAULT_SCHEMA=${DEFAULT_SCHEMA}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - MONGODB_DATABASE=zimeet
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FIREBASE_ADMIN_SDK_PATH=${FIREBASE_ADMIN_SDK_PATH}
    ports:
      - "8080:8080"
    networks:
      - gdg_network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_started

  # Worker WAS (개발환경)
  backend-worker-dev:
    container_name: backend-worker
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=worker,dev
      - SERVER_PORT=8080
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
      - DEFAULT_SCHEMA=${DEFAULT_SCHEMA}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - MONGODB_DATABASE=zimeet
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FIREBASE_ADMIN_SDK_PATH=${FIREBASE_ADMIN_SDK_PATH}
    ports:
      - "8081:8080"  # 디버깅용 포트
    networks:
      - gdg_network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      mongodb:
        condition: service_started
    restart: unless-stopped

networks:
  gdg_network:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: