services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - zimeet_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend-worker-1:
    container_name: backend-worker-1
    image: ${DOCKERHUB_USERNAME}/zimeet:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=worker
      - MYSQL_USER=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${PROD_DB_PASSWORD}
      - MYSQL_URL=jdbc:mysql://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}?serverTimezone=UTC
    networks:
      - zimeet_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend-worker-2:
    container_name: backend-worker-2
    image: ${DOCKERHUB_USERNAME}/zimeet:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=worker
      - MYSQL_USER=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${PROD_DB_PASSWORD}
      - MYSQL_URL=jdbc:mysql://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}?serverTimezone=UTC
    networks:
      - zimeet_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  zimeet_network:
    external: true

volumes:
  rabbitmq_data: