services:
  redis:
    container_name: redis1
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - zimeet_network
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 60s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27018:27017"
    networks:
      - zimeet_network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 60s
      timeout: 10s
      retries: 3

  backend-blue:
    container_name: backend-blue
    image: ${DOCKERHUB_USERNAME}/zimeet:latest
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_USER=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${PROD_DB_PASSWORD}
      - MYSQL_URL=jdbc:mysql://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}?serverTimezone=UTC&sslMode=PREFERRED&allowPublicKeyRetrieval=true
    networks:
      - zimeet_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  backend-green:
    container_name: backend-green
    image: ${DOCKERHUB_USERNAME}/zimeet:latest
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_USER=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${PROD_DB_PASSWORD}
      - MYSQL_URL=jdbc:mysql://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}?serverTimezone=UTC&sslMode=PREFERRED&allowPublicKeyRetrieval=true
    networks:
      - zimeet_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "90:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/backend_upstream.conf:/etc/nginx/backend_upstream.conf:ro
      - /etc/letsencrypt/live/api.zimeet.store:/etc/letsencrypt/live/api.zimeet.store:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    environment:
      - TZ=Asia/Seoul
    networks:
      - zimeet_network
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-kf", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  zimeet_network:
    external: true

volumes:
  mongodb_data: