spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${PROD_DB_ENDPOINT}:3306/gdg?serverTimezone=UTC
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: false             # prod 환경에서는 SQL 출력 비활성화
  data:
    redis:
      host: redis1
      port: 6379
      repositories:
        enabled: false
    mongodb:
      host: mongodb1
      port: 27017
      database: zimeet
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/, file:/static/

firebase:
  admin-sdk: firebase/zi-meet-firebase-adminsdk-fbsvc-f026a2abf0.json