spring:
  config:
    activate:
      on-profile: worker

logging:
  level:
    com.gdg.z_meet: INFO
    org.springframework.amqp: DEBUG
  pattern:
    console: "[WORKER] %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"