spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${PROD_DB_ENDPOINT}:3306/gdg?serverTimezone=UTC
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: false
  data:
    redis:
      host: redis1
      port: 6379
      repositories:
        enabled: false
    mongodb:
      host: mongodb1
      port: 27017
      database: zimeet
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/, file:/static/

# RabbitMQ Consumer 비활성화
api:
  enabled: true             # API 서버 활성화

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:1234}
    virtual-host: /

    listener:
      simple:
        enabled: false       # API 서버에서는 Consumer 비활성화
        prefetch: 10         # (비활성화여도 기본값 정의는 가능)
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 5
        
scheduling:
  enabled: true