spring:
  profiles:
    active: worker
    include: default

  # RabbitMQ Consumer 활성화
  rabbitmq:
    listener:
      simple:
        enabled: true

worker:
  enabled: true

server:
  servlet:
    context-path: /worker   # API 서버 기능 제한 (worker 전용 경로)

scheduling:
  enabled: false            # 스케줄러 비활성화 (API 서버에서만 실행)