spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show_sql: false

  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      host: mongodb
      port: 27017
      database: ${MONGODB_DATABASE:zimeet}

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=3600s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: 86400000

kakao:
  pay:
    secret-key: DEV67E80F0AE00ADB148D9D81F39875B9CEDFE1B
    cid: TC0ONETIME
    ready-url: https://open-api.kakaopay.com/online/v1/payment/ready
    approve-url: https://open-api.kakaopay.com/online/v1/payment/approve

firebase:
  admin-sdk: ${FIREBASE_ADMIN_SDK_PATH}