management:
  endpoints:
    web:
      exposure:
        include: health      # Actuator에서 health 엔드포인트를 활성화
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://${DEFAULT_URL}:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
  flyway:
    enabled: false     # dev 환경에서는 flyway 사용 x
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: ${DEFAULT_URL}
      port: 27017
      database: ${DEFAULT_SCHEMA}

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=3600s
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  use-fqn: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  cache:
    disabled: true

jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: 86400000

kakao:
  pay:
    secret-key: DEV67E80F0AE00ADB148D9D81F39875B9CEDFE1B
    cid: TC0ONETIME
    ready-url: https://open-api.kakaopay.com/online/v1/payment/ready
    approve-url: https://open-api.kakaopay.com/online/v1/payment/approve

firebase:
  admin-sdk: firebase/zi-meet-firebase-adminsdk-fbsvc-f026a2abf0.json