global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'backend-blue'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-blue:8080']

  - job_name: 'backend-green'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-green:8080']

  - job_name: 'backend-worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-worker:8080']