apiVersion: 1

groups:
  - orgId: 1
    name: error_alerts
    folder: Logs
    interval: 1m
    rules:
      - uid: error_fatal_alert
        title: ERROR/FATAL Log Alert
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              expr: 'sum(count_over_time({container=~"backend-blue|backend-green|backend-worker"} |~ "ERROR|FATAL" !~ "Failed to send message to MessageChannel" [1m]))'
              refId: A
          - refId: C
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              type: reduce
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: 'ERROR 또는 FATAL 레벨 로그가 감지되었습니다.'
          summary: '애플리케이션에서 심각한 에러가 발생했습니다.'
        labels:
          severity: critical
        notificationSettings:
          receiver: discord